# Android CircleCI configuration file
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "framework/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "framework/build.gradle" }}
      - run:
          name: Assemble Debug Build
          command: ./gradlew assembleDevDebug --info
      - store_artifacts:
          path: app/build/outputs/apk/dev/debug/app-dev-debug.apk
          destination: apks/los-dev-debug.apk
      - run:
          name: Run Unit Tests
          command: ./gradlew testDevDebugUnitTest jacocoTestDevDebugUnitTestReport
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
          destination: test-results
      - run:
          name: Uploading Test Results To Codecov
          command: bash <(curl -s https://codecov.io/bash) -t 3f755b80-cb56-4c19-8573-122f76c23279